# Generated by Django 4.2.16 on 2026-06-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tech', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_file_path', models.CharField(max_length=500)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='tech.encryptedfile')),
                ('production_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download History',
                'verbose_name_plural': 'Download Histories',
                'db_table': 'download_history',
            },
        ),
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_key_requests', to=settings.AUTH_USER_MODEL)),
                ('encrypted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_requests', to='tech.encryptedfile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Request',
                'verbose_name_plural': 'Key Requests',
                'db_table': 'key_requests',
                'indexes': [models.Index(fields=['status'], name='key_request_status_ed6dc0_idx')],
            },
        ),
    ]
