# Generated by Django 4.2.16 on 2026-06-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tech', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENCRYPTED', 'Encrypted'), ('DECRYPTED', 'Decrypted')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_history', to='tech.encryptedfile')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encryption_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encryption History',
                'verbose_name_plural': 'Encryption Histories',
                'db_table': 'encryption_history',
                'indexes': [models.Index(fields=['action'], name='encryption__action_6616e7_idx')],
            },
        ),
    ]
