# Generated by Django 4.2.16 on 2026-06-17 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('uploaded_file', models.FileField(upload_to='uploads/csv_xlsx/')),
                ('file_type', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='RejectedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_record', to='purchase.material')),
                ('purchase_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rejected Material',
                'verbose_name_plural': 'Rejected Materials',
                'db_table': 'rejected_materials',
            },
        ),
        migrations.CreateModel(
            name='ApprovedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('edited_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sent_to_tech', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_record', to='purchase.material')),
                ('purchase_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approved Material',
                'verbose_name_plural': 'Approved Materials',
                'db_table': 'approved_materials',
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status'], name='materials_status_bf1b15_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['vendor', 'status'], name='materials_vendor__54e221_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['expiry_date'], name='materials_expiry__700e76_idx'),
        ),
        migrations.AddIndex(
            model_name='approvedmaterial',
            index=models.Index(fields=['sent_to_tech'], name='approved_ma_sent_to_8f300d_idx'),
        ),
    ]
