# Generated by Django 4.2.16 on 2026-06-21 06:27
from django.db import migrations, models


def backfill_user_status(apps, schema_editor):
    """
    Existing users predate the status field. Backfill based on their
    current is_approved/is_active combination:
      - is_approved=True (regardless of is_active) -> APPROVED
        (an approved-then-deactivated user is still APPROVED status;
        is_active separately controls whether they can log in)
      - is_approved=False -> PENDING
        (we cannot retroactively distinguish "never reviewed" from
        "explicitly rejected" using the old two-boolean scheme, which
        is exactly the bug this migration fixes going forward. PENDING
        is the safer default: it surfaces these accounts to Admin for
        a fresh decision rather than silently treating them as
        rejected, which could incorrectly lock out a legitimately
        pending account.)
    """
    User = apps.get_model('accounts', 'User')

    User.objects.filter(is_approved=True).update(status='APPROVED')
    User.objects.filter(is_approved=False).update(status='PENDING')


def reverse_backfill(apps, schema_editor):
    """No-op: reversing this migration just drops the column, no data to restore."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_alter_role_options_alter_user_options_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_status_9ca66f_idx'),
        ),
        migrations.RunPython(backfill_user_status, reverse_backfill),
    ]