import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { getEncryptionDetail } from '../../api/techApi';

function EncryptionDetails() {
  const { id } = useParams();
  const [detail, setDetail] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getEncryptionDetail(id)
      .then((res) => setDetail(res.data.data))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) return <div className="container mt-5">Loading...</div>;
  if (!detail) return <div className="container mt-5 alert alert-danger">Record not found.</div>;

  return (
    <div className="container mt-5" style={{ maxWidth: '600px' }}>
      <h2 className="mb-4">Encryption Detail</h2>
      <div className="card">
        <div className="card-body">
          <p><strong>Material:</strong> {detail.material_name}</p>
          <p><strong>Vendor:</strong> {detail.vendor_name}</p>
          <p><strong>Generated By:</strong> {detail.generated_by_name}</p>
          <p><strong>Status:</strong> {detail.status}</p>
          <p><strong>Encrypted:</strong> {detail.has_encrypted_file ? 'Yes' : 'No'}</p>
          <p><strong>Date:</strong> {new Date(detail.created_at).toLocaleString()}</p>
        </div>
      </div>
    </div>
  );
}

export default EncryptionDetails;