import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getEncryptionDetail } from '../../services/techApi';
import Loader from '../../components/admin/Loader';
import ErrorState from '../../components/admin/ErrorState';

function EncryptionDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [detail, setDetail] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    getEncryptionDetail(id)
      .then((res) => setDetail(res.data.data))
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) return <Loader />;
  if (error || !detail) return <ErrorState message="Record not found." />;

  return (
    <div style={{ maxWidth: '500px' }}>
      <button className="btn btn-link ps-0 mb-3" onClick={() => navigate('/tech/encryption-history')}>&larr; Back to History</button>
      <h2 className="mb-4">Encryption Detail</h2>
      <div className="card">
        <div className="card-body">
          <p><strong>Material:</strong> {detail.material_name}</p>
          <p><strong>Vendor:</strong> {detail.vendor_name}</p>
          <p><strong>Generated By:</strong> {detail.generated_by_name}</p>
          <p><strong>Status:</strong> <span className="badge bg-info text-dark">{detail.status}</span></p>
          <p><strong>Encrypted:</strong> {detail.has_encrypted_file ? 'Yes' : 'No'}</p>
          <p><strong>Date:</strong> {new Date(detail.created_at).toLocaleString()}</p>
        </div>
      </div>
    </div>
  );
}

export default EncryptionDetail;