import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getEncryptionHistory } from '../../services/techApi';
import Loader from '../../components/admin/Loader';

function EncryptionHistory() {
  const [records, setRecords] = useState([]);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [page, setPage] = useState(1);
  const [pagination, setPagination] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchData = () => {
    setLoading(true);
    getEncryptionHistory({ search, status: statusFilter, page })
      .then((res) => {
        setRecords(res.data.data);
        setPagination(res.data.pagination);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, statusFilter]);

  return (
    <div>
      <h2 className="mb-4">Encryption History</h2>

      <div className="d-flex gap-2 mb-3 flex-wrap">
        <form onSubmit={(e) => { e.preventDefault(); setPage(1); fetchData(); }} className="d-flex gap-2">
          <input type="text" className="form-control" placeholder="Search material" value={search} onChange={(e) => setSearch(e.target.value)} />
          <button type="submit" className="btn btn-outline-primary">Search</button>
        </form>
        <select className="form-select w-auto" value={statusFilter} onChange={(e) => { setStatusFilter(e.target.value); setPage(1); }}>
          <option value="">All Status</option>
          <option value="TXT_GENERATED">TXT Generated</option>
          <option value="ENCRYPTED">Encrypted</option>
          <option value="KEY_REQUESTED">Key Requested</option>
          <option value="KEY_APPROVED">Key Approved</option>
          <option value="DECRYPTED">Decrypted</option>
        </select>
      </div>

      {loading ? (
        <Loader />
      ) : records.length === 0 ? (
        <p className="text-muted">No encryption records found.</p>
      ) : (
        <>
          <table className="table table-striped">
            <thead>
              <tr>
                <th>Material</th>
                <th>Vendor</th>
                <th>Encrypted</th>
                <th>Status</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {records.map((r) => (
                <tr key={r.id}>
                  <td>{r.material_name}</td>
                  <td>{r.vendor_name}</td>
                  <td>{r.has_encrypted_file ? 'Yes' : 'No'}</td>
                  <td><span className="badge bg-info text-dark">{r.status}</span></td>
                  <td>{r.generated_by_name}</td>
                  <td className="text-muted small">{new Date(r.created_at).toLocaleString()}</td>
                  <td><Link to={`/tech/history/${r.id}`} className="btn btn-sm btn-outline-primary">View</Link></td>
                </tr>
              ))}
            </tbody>
          </table>

          {pagination && pagination.total_pages > 1 && (
            <div className="d-flex justify-content-between">
              <button className="btn btn-outline-secondary" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>Previous</button>
              <span>Page {pagination.current_page} of {pagination.total_pages}</span>
              <button className="btn btn-outline-secondary" disabled={page >= pagination.total_pages} onClick={() => setPage((p) => p + 1)}>Next</button>
            </div>
          )}
        </>
      )}
    </div>
  );
}

export default EncryptionHistory;