import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getEncryptionHistory } from '../../api/techApi';

function EncryptionHistory() {
  const [records, setRecords] = useState([]);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [pagination, setPagination] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchHistory = () => {
    setLoading(true);
    getEncryptionHistory({ search, page })
      .then((res) => {
        setRecords(res.data.data);
        setPagination(res.data.pagination);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchHistory();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page]);

  return (
    <div className="container mt-5">
      <h2 className="mb-4">Encryption History</h2>

      <form onSubmit={(e) => { e.preventDefault(); setPage(1); fetchHistory(); }} className="mb-3 d-flex gap-2">
        <input
          type="text"
          className="form-control"
          placeholder="Search material name"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <button type="submit" className="btn btn-outline-primary">Search</button>
      </form>

      {loading ? (
        <p>Loading...</p>
      ) : (
        <>
          <table className="table table-striped">
            <thead>
              <tr>
                <th>Material</th>
                <th>Vendor</th>
                <th>Generated By</th>
                <th>Status</th>
                <th>Date</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {records.map((r) => (
                <tr key={r.id}>
                  <td>{r.material_name}</td>
                  <td>{r.vendor_name}</td>
                  <td>{r.generated_by_name}</td>
                  <td>{r.status}</td>
                  <td>{new Date(r.created_at).toLocaleString()}</td>
                  <td><Link to={`/tech/history/${r.id}`} className="btn btn-sm btn-primary">View</Link></td>
                </tr>
              ))}
            </tbody>
          </table>

          {pagination && (
            <div className="d-flex justify-content-between">
              <button className="btn btn-outline-secondary" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>Previous</button>
              <span>Page {pagination.current_page} of {pagination.total_pages}</span>
              <button className="btn btn-outline-secondary" disabled={page >= pagination.total_pages} onClick={() => setPage((p) => p + 1)}>Next</button>
            </div>
          )}
        </>
      )}
    </div>
  );
}

export default EncryptionHistory;