import React, { useEffect, useState } from 'react';
import { getTechDashboard } from '../../api/techApi';

function TechDashboard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getTechDashboard()
      .then((res) => setData(res.data))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="container mt-5">Loading...</div>;
  if (!data) return <div className="container mt-5 alert alert-danger">Failed to load dashboard.</div>;

  const cards = [
    { label: 'Materials Received', value: data.stats.materials_received, color: 'info' },
    { label: 'TXT Files Generated', value: data.stats.txt_files_generated, color: 'secondary' },
    { label: 'Files Encrypted', value: data.stats.files_encrypted, color: 'success' },
    { label: 'Pending Admin Approval', value: data.stats.pending_admin_approval, color: 'warning' },
    { label: 'Completed Encryptions', value: data.stats.completed_encryptions, color: 'primary' },
  ];

  return (
    <div className="container mt-5">
      <h2 className="mb-4">Tech Dashboard</h2>
      <div className="row g-3 mb-4">
        {cards.map((card) => (
          <div className="col-md-2 col-sm-4" key={card.label}>
            <div className={`card border-${card.color}`}>
              <div className="card-body">
                <h6 className="card-subtitle text-muted small">{card.label}</h6>
                <h3 className={`text-${card.color}`}>{card.value}</h3>
              </div>
            </div>
          </div>
        ))}
      </div>

      <h4>Recent Encryptions</h4>
      <table className="table table-striped">
        <thead>
          <tr>
            <th>Material</th>
            <th>Vendor</th>
            <th>Encrypted</th>
            <th>Status</th>
            <th>Generated By</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {data.recent_encryptions.map((e) => (
            <tr key={e.id}>
              <td>{e.material_name}</td>
              <td>{e.vendor_name}</td>
              <td>{e.has_encrypted_file ? 'Yes' : 'No'}</td>
              <td>{e.status}</td>
              <td>{e.generated_by_name}</td>
              <td>{new Date(e.created_at).toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default TechDashboard;