# Generated by Django 4.2.16 on 2026-06-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(default='Food Processing System', max_length=255)),
                ('company_name', models.CharField(default='', max_length=255)),
                ('max_upload_size_mb', models.IntegerField(default=10)),
                ('allowed_file_types', models.CharField(default='.csv,.xlsx', max_length=255)),
                ('session_timeout_minutes', models.IntegerField(default=1440)),
                ('password_min_length', models.IntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
