import csv
import io
from django.http import HttpResponse
from openpyxl import Workbook
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from apps.accounts.models import User
from apps.vendors.models import VendorProfile
from apps.purchase.models import Material
from apps.tech.models import EncryptedFile
from apps.production.models import DownloadHistory
from apps.audit.models import AuditLog


REPORT_BUILDERS = {}


def _user_report_rows():
    header = ['ID', 'Name', 'Email', 'Role', 'Active', 'Approved', 'Joined']
    rows = [header]
    for u in User.objects.select_related('role').all():
        rows.append([
            u.id,
            f'{u.first_name} {u.last_name}'.strip() or u.username,
            u.email,
            u.role.name if u.role else '',
            u.is_active,
            u.is_approved,
            u.date_joined.strftime('%Y-%m-%d %H:%M'),
        ])
    return rows


def _vendor_report_rows():
    header = ['Vendor ID', 'Company', 'Email', 'Phone', 'Approved']
    rows = [header]
    for v in VendorProfile.objects.select_related('user').all():
        rows.append([
            v.user.id,
            v.company_name,
            v.user.email,
            v.user.phone or '',
            v.user.is_approved,
        ])
    return rows


def _material_report_rows():
    header = ['Material ID', 'Name', 'Quantity', 'Cost', 'Supplier', 'Status', 'Vendor']
    rows = [header]
    for m in Material.objects.select_related('vendor').all():
        rows.append([
            m.material_code,
            m.material_name,
            float(m.quantity),
            float(m.cost),
            m.supplier,
            m.status,
            m.vendor.email,
        ])
    return rows


def _encryption_report_rows():
    header = ['ID', 'Material', 'Vendor', 'Status', 'Generated By', 'Date']
    rows = [header]
    for e in EncryptedFile.objects.select_related('approved_material__material__vendor', 'generated_by').all():
        rows.append([
            e.id,
            e.approved_material.material.material_name,
            e.approved_material.material.vendor.email,
            e.status,
            e.generated_by.email if e.generated_by else '',
            e.created_at.strftime('%Y-%m-%d %H:%M'),
        ])
    return rows


def _download_report_rows():
    header = ['ID', 'User', 'File', 'Downloaded At']
    rows = [header]
    for d in DownloadHistory.objects.select_related('production_user').all():
        rows.append([
            d.id,
            d.production_user.email,
            d.downloaded_file_path,
            d.downloaded_at.strftime('%Y-%m-%d %H:%M'),
        ])
    return rows


def _audit_report_rows():
    header = ['ID', 'User', 'Role', 'Action', 'Description', 'Timestamp']
    rows = [header]
    for a in AuditLog.objects.select_related('user').all():
        rows.append([
            a.id,
            a.user.email if a.user else '',
            a.role or '',
            a.action,
            a.description or '',
            a.timestamp.strftime('%Y-%m-%d %H:%M'),
        ])
    return rows


REPORT_BUILDERS = {
    'users': _user_report_rows,
    'vendors': _vendor_report_rows,
    'materials': _material_report_rows,
    'encryption': _encryption_report_rows,
    'downloads': _download_report_rows,
    'audit': _audit_report_rows,
}


def get_report_rows(report_type):
    builder = REPORT_BUILDERS.get(report_type)
    if not builder:
        return None
    return builder()


def export_csv(report_type):
    rows = get_report_rows(report_type)
    if rows is None:
        return None

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{report_type}_report.csv"'
    writer = csv.writer(response)
    for row in rows:
        writer.writerow(row)
    return response


def export_excel(report_type):
    rows = get_report_rows(report_type)
    if rows is None:
        return None

    wb = Workbook()
    ws = wb.active
    ws.title = report_type.capitalize()
    for row in rows:
        ws.append(row)

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)

    response = HttpResponse(buffer.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename="{report_type}_report.xlsx"'
    return response


def export_pdf(report_type):
    rows = get_report_rows(report_type)
    if rows is None:
        return None

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    y = height - 50
    p.setFont('Helvetica-Bold', 14)
    p.drawString(50, y, f'{report_type.capitalize()} Report')
    y -= 30

    p.setFont('Helvetica', 8)
    for row in rows:
        line = ' | '.join(str(cell) for cell in row)
        if y < 50:
            p.showPage()
            y = height - 50
            p.setFont('Helvetica', 8)
        p.drawString(50, y, line[:140])
        y -= 14

    p.save()
    buffer.seek(0)

    response = HttpResponse(buffer.read(), content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{report_type}_report.pdf"'
    return response