from django.urls import path
from .views import (
    AdminDashboardView,
    AdminUsersView,
    AdminUserDetailView,
    AdminApproveUserView,
    AdminRejectUserView,
    AdminActivateUserView,
    AdminDeactivateUserView,
    AdminKeyRequestsView,
    AdminKeyRequestApproveView,
    AdminKeyRequestRejectView,
    AdminEncryptionHistoryView,
    AdminDownloadHistoryView,
    AdminAuditLogsView,
    AdminNotificationsView,
    AdminNotificationMarkReadView,
    AdminReportsView,
    AdminSystemSettingsView,
)

urlpatterns = [
    path('dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('users/', AdminUsersView.as_view(), name='admin-users'),
    path('users/<int:user_id>/', AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('users/<int:user_id>/approve/', AdminApproveUserView.as_view(), name='admin-user-approve'),
    path('users/<int:user_id>/reject/', AdminRejectUserView.as_view(), name='admin-user-reject'),
    path('users/<int:user_id>/activate/', AdminActivateUserView.as_view(), name='admin-user-activate'),
    path('users/<int:user_id>/deactivate/', AdminDeactivateUserView.as_view(), name='admin-user-deactivate'),
    path('key-requests/', AdminKeyRequestsView.as_view(), name='admin-key-requests'),
    path('key-request/<int:key_request_id>/approve/', AdminKeyRequestApproveView.as_view(), name='admin-key-request-approve'),
    path('key-request/<int:key_request_id>/reject/', AdminKeyRequestRejectView.as_view(), name='admin-key-request-reject'),
    path('encryption-history/', AdminEncryptionHistoryView.as_view(), name='admin-encryption-history'),
    path('download-history/', AdminDownloadHistoryView.as_view(), name='admin-download-history'),
    path('audit-logs/', AdminAuditLogsView.as_view(), name='admin-audit-logs'),
    path('notifications/', AdminNotificationsView.as_view(), name='admin-notifications'),
    path('notifications/<int:notification_id>/read/', AdminNotificationMarkReadView.as_view(), name='admin-notification-read'),
    path('reports/', AdminReportsView.as_view(), name='admin-reports'),
    path('system-settings/', AdminSystemSettingsView.as_view(), name='admin-system-settings'),
]