# Generated by Django 4.2.16 on 2026-06-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/original/')),
                ('txt_file', models.FileField(upload_to='uploads/txt/')),
                ('encrypted_file', models.FileField(upload_to='uploads/encrypted/')),
                ('status', models.CharField(choices=[('ENCRYPTED', 'Encrypted'), ('KEY_REQUESTED', 'Key Requested'), ('KEY_SHARED', 'Key Shared'), ('DECRYPTED', 'Decrypted'), ('DOWNLOADED', 'Downloaded')], default='ENCRYPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_file', to='purchase.approvedmaterial')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_encrypted_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encrypted File',
                'verbose_name_plural': 'Encrypted Files',
                'db_table': 'encrypted_files',
            },
        ),
        migrations.CreateModel(
            name='AESKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_value_encrypted', models.TextField()),
                ('iv', models.CharField(max_length=32)),
                ('sent_to_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aes_key', to='tech.encryptedfile')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_aes_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AES Key',
                'verbose_name_plural': 'AES Keys',
                'db_table': 'aes_keys',
            },
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['status'], name='encrypted_f_status_4f204b_idx'),
        ),
    ]
