# Generated by Django 4.2.16 on 2026-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TXT_GENERATED', 'TXT Generated'), ('ENCRYPTED', 'Encrypted'), ('KEY_REQUESTED', 'Key Requested'), ('KEY_APPROVED', 'Key Approved'), ('DECRYPTED', 'Decrypted')], default='PENDING', max_length=20),
        ),
    ]
